version: '3'
services:
  proxy:
    build:
      context: proxy
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"
    depends_on:
      - front
      - back-end
    restart: always
  back-end:
    build:
      context: back-end
    image: softy-pinko-back-end:task6
    ports: 
      - "5252" 
    restart: always
  front:
    build: 
      context: front-end
    image: softy-pinko-front-end:task6
    ports: 
      - "9000"
    depends_on: 
      - back-end
    restart: always